services:
  db:
    container_name: myfilms
    image: postgres:18
    ports:
      - "${DB_PORT}:${DB_PORT}"    
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    restart: always
    volumes:
      - ./pgdata:/var/lib/postgresql/docker
